version: '3.7'
services:

  db:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "nc -z localhost 3306",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: todos
  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:8080

  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    image: node:lts-alpine3.19
    user: "node"
    working_dir: /home/node/app
    environment:
      MYSQL_HOST: db
      MYSQL_DB: todos
    volumes:
      - ./gate-simulator:/home/node/app
    depends_on:
      - db
    expose:
      - "9999"
    command: "npm start"
